# Generated by Django 5.0.1 on 2024-01-28 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id_kategorie', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kosik',
            fields=[
                ('id_kosiku', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id_objednavky', models.AutoField(primary_key=True, serialize=False)),
                ('datum_objednavky', models.DateTimeField(auto_now_add=True)),
                ('stav', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id_produktu', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('popis', models.TextField(null=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skladove_zasoby', models.IntegerField(null=True)),
                ('datum_vytvoreni', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_kategorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.kategorie')),
            ],
            options={
                'ordering': ['-datum_vytvoreni'],
            },
        ),
        migrations.CreateModel(
            name='PolozkaKosiku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField(default=1)),
                ('kosik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kosik')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Novinka',
            fields=[
                ('id_novinky', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('obsah', models.TextField(null=True)),
                ('produkty', models.ManyToManyField(to='shop.produkt')),
            ],
        ),
        migrations.AddField(
            model_name='kosik',
            name='obsah_kosiku',
            field=models.ManyToManyField(through='shop.PolozkaKosiku', to='shop.produkt'),
        ),
        migrations.CreateModel(
            name='ProduktObjednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField()),
                ('id_objednavky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.objednavka')),
                ('id_produktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='HistorieObjednavek',
            fields=[
                ('id_historie', models.AutoField(primary_key=True, serialize=False)),
                ('stav', models.CharField(max_length=255)),
                ('datum_zmeny', models.DateTimeField()),
                ('id_objednavky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.objednavka')),
            ],
            options={
                'indexes': [models.Index(fields=['id_objednavky'], name='shop_histor_id_obje_e26167_idx')],
            },
        ),
        migrations.CreateModel(
            name='Doprava',
            fields=[
                ('id_dopravy', models.AutoField(primary_key=True, serialize=False)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metoda_dopravy', models.CharField(max_length=255)),
                ('datum_dopravy', models.DateTimeField()),
                ('id_objednavky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.objednavka')),
            ],
            options={
                'indexes': [models.Index(fields=['id_objednavky'], name='shop_doprav_id_obje_c0e051_idx')],
            },
        ),
        migrations.CreateModel(
            name='Platba',
            fields=[
                ('id_platby', models.AutoField(primary_key=True, serialize=False)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metoda_platby', models.CharField(max_length=255)),
                ('datum_platby', models.DateTimeField()),
                ('id_objednavky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.objednavka')),
            ],
            options={
                'indexes': [models.Index(fields=['id_objednavky'], name='shop_platba_id_obje_434e64_idx')],
            },
        ),
        migrations.CreateModel(
            name='ObrazekProduktu',
            fields=[
                ('id_obrazku', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_obrazku', models.CharField(max_length=255)),
                ('id_produktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produkt')),
            ],
            options={
                'indexes': [models.Index(fields=['id_produktu'], name='shop_obraze_id_prod_901c33_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id_recenze', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(null=True)),
                ('datum_recenze', models.DateTimeField()),
                ('id_produktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produkt')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['id_produktu'], name='shop_recenz_id_prod_4c25a6_idx'), models.Index(fields=['user'], name='shop_recenz_user_id_9b56d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Registrace',
            fields=[
                ('id_registrace', models.AutoField(primary_key=True, serialize=False)),
                ('heslo', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='shop_regist_user_id_d582cc_idx')],
            },
        ),
    ]
