# Generated by Django 5.0.1 on 2024-01-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produktobjednavka',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Kosik',
            fields=[
                ('id_kosiku', models.AutoField(primary_key=True, serialize=False)),
                ('id_zakaznika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.zakaznik')),
            ],
        ),
        migrations.CreateModel(
            name='PolozkaKosiku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.IntegerField(default=1)),
                ('kosik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kosik')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produkt')),
            ],
        ),
        migrations.AddField(
            model_name='kosik',
            name='obsah_kosiku',
            field=models.ManyToManyField(through='shop.PolozkaKosiku', to='shop.produkt'),
        ),
    ]
