# Generated by Django 5.0.1 on 2024-02-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_kosik_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='nazev_obrazku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ObrazekProduktu',
        ),
    ]
