# Generated by Django 5.0.1 on 2024-02-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_produkt_nazev_obrazku_delete_obrazekproduktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='nazev_obrazku',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
