# Generated by Django 5.0.1 on 2024-01-21 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_kosik_id_zakaznika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kosik',
            name='id_zakaznika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.zakaznik'),
        ),
        migrations.AlterField(
            model_name='recenze',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
