# Generated by Django 5.0.1 on 2024-01-25 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_kosik_id_zakaznika_alter_recenze_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkt',
            options={'ordering': ['-datum_vytvoreni']},
        ),
        migrations.AddField(
            model_name='produkt',
            name='datum_vytvoreni',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Novinka',
            fields=[
                ('id_novinky', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('obsah', models.TextField(null=True)),
                ('produkty', models.ManyToManyField(to='shop.produkt')),
            ],
        ),
    ]
