# Generated by Django 5.0.1 on 2024-02-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_produkt_nazev_obrazku'),
    ]

    operations = [
        migrations.AddField(
            model_name='polozkakosiku',
            name='celkova_cena',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
