# Generated by Django 5.0.1 on 2024-02-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_polozkakosiku_celkova_cena_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polozkakosiku',
            options={'verbose_name_plural': 'položky košíku'},
        ),
        migrations.RenameField(
            model_name='polozkakosiku',
            old_name='produkt',
            new_name='polzkaprodukt',
        ),
    ]
