# Generated by Django 5.0.1 on 2024-02-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_polozkakosiku_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polozkakosiku',
            old_name='polzkaprodukt',
            new_name='produkt',
        ),
    ]
