# Generated by Django 5.0.1 on 2024-02-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_polzkaprodukt_polozkakosiku_produkt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polozkakosiku',
            old_name='kosik',
            new_name='id_kosik',
        ),
        migrations.RenameField(
            model_name='polozkakosiku',
            old_name='produkt',
            new_name='id_produkt',
        ),
    ]
