# Generated by Django 5.0.1 on 2024-02-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_kosik_polozkakosiku_id_kosik_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polozkakosiku',
            old_name='id_kosik',
            new_name='kosik',
        ),
    ]
