# Generated by Django 5.0.1 on 2024-02-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_id_kosik_polozkakosiku_kosik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polozkakosiku',
            old_name='kosik',
            new_name='id_kosik',
        ),
    ]
