# Generated by Django 5.0.1 on 2024-02-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_kosik_polozkakosiku_id_kosik'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doprava',
            name='shop_doprav_id_obje_c0e051_idx',
        ),
        migrations.RemoveIndex(
            model_name='platba',
            name='shop_platba_id_obje_434e64_idx',
        ),
        migrations.RemoveField(
            model_name='doprava',
            name='datum_dopravy',
        ),
        migrations.RemoveField(
            model_name='doprava',
            name='id_objednavky',
        ),
        migrations.RemoveField(
            model_name='platba',
            name='datum_platby',
        ),
        migrations.RemoveField(
            model_name='platba',
            name='id_objednavky',
        ),
        migrations.RemoveField(
            model_name='platba',
            name='suma',
        ),
        migrations.AddField(
            model_name='objednavka',
            name='doprava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.doprava'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='platba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.platba'),
        ),
    ]
