# Generated by Django 5.0.1 on 2024-02-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_doprava_shop_doprav_id_obje_c0e051_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platba',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
