# Generated by Django 5.0.1 on 2024-02-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_produkt_cena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objednavka',
            old_name='doprava',
            new_name='vybrana_doprava',
        ),
        migrations.RenameField(
            model_name='objednavka',
            old_name='platba',
            new_name='vybrana_platba',
        ),
    ]
