# Generated by Django 5.0.1 on 2024-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_doprava_objednavka_vybrana_doprava_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objednavka',
            name='vybrana_doprava',
        ),
        migrations.RemoveField(
            model_name='objednavka',
            name='vybrana_platba',
        ),
        migrations.AddField(
            model_name='kosik',
            name='vybrana_doprava',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kosik',
            name='vybrana_platba',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
