# Generated by Django 5.0.1 on 2024-02-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_objednavka_vybrana_doprava_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosik',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='kosik',
            name='cena_dopravy',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='kosik',
            name='cena_platby',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
