# Generated by Django 5.0.1 on 2024-02-11 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_kosik_cena_kosik_cena_dopravy_kosik_cena_platby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kosik',
            name='vybrana_doprava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.doprava'),
        ),
        migrations.AlterField(
            model_name='kosik',
            name='vybrana_platba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.platba'),
        ),
    ]
