# Generated by Django 5.0.1 on 2024-02-11 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_kosik_vybrana_doprava_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objednavka',
            name='vybrana_doprava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.doprava'),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='vybrana_platba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.platba'),
        ),
    ]
